# Generated by Django 3.2.15 on 2022-09-15 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trail', '0002_star'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star',
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1500),
        ),
    ]
